# Generated by Django 4.2.7 on 2023-12-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universitycampus',
            options={'verbose_name_plural': 'University Campuses'},
        ),
        migrations.AlterField(
            model_name='universitycampus',
            name='campus_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
