# Generated by Django 4.2 on 2023-11-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181101_2355'),
        ('products', '0003_alter_product_type'),
    ]

    operations = [
    ]
